site_name: llikdowk's stuff
site_url: https://llikdowk.github.io
nav:
  - Home: index.md
  - About: about.md
theme:
  name: mkdocs 
  features:
    - search.suggest
    - search.highlight
    - search.share
  palette: 
    scheme: slate
markdown_extensions:
  - admonition
plugins:
  - search:
      lang: en
